from __future__ import annotations

import base64
import os
import pwd
import re
import shlex
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

from app.command import CommandResult, run_command
from app.filesystem import chown_root_if_possible, has_mode, write_atomic
from app.ssh_hardening import (
    confirm,
    format_ssh_host,
    publickey_only_ssh_command,
    publickey_only_ssh_instruction_lines,
    server_address_from_ssh_connection,
)


USERNAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")
AUTHORIZED_KEYS_NAME = "authorized_keys"
LOGIN_DEFS = Path(os.environ.get("VPS_BOOTSTRAP_LOGIN_DEFS", "/etc/login.defs"))
DEFAULT_UID_MIN = 1000
SUDOERS_FILE = Path(os.environ.get("VPS_BOOTSTRAP_SUDOERS_FILE", "/etc/sudoers"))
MANAGED_SUDOERS = Path(os.environ.get("VPS_BOOTSTRAP_ADMIN_SUDOERS", "/etc/sudoers.d/10-vps-bootstrap-admin"))
SUDO_MODE_PASSWORD_REQUIRED = "password_required"
SUDO_MODE_NOPASSWD = "nopasswd"
SUDOERS_HEADER = "# Managed by vps-bootstrap. Do not edit this file directly."
SUPPORTED_KEY_TYPES = {
    "ssh-ed25519",
    "ssh-rsa",
    "ecdsa-sha2-nistp256",
    "ecdsa-sha2-nistp384",
    "ecdsa-sha2-nistp521",
    "sk-ssh-ed25519@openssh.com",
    "sk-ecdsa-sha2-nistp256@openssh.com",
    "ssh-dss",
    "ssh-ed25519-cert-v01@openssh.com",
    "ssh-rsa-cert-v01@openssh.com",
    "ecdsa-sha2-nistp256-cert-v01@openssh.com",
    "ecdsa-sha2-nistp384-cert-v01@openssh.com",
    "ecdsa-sha2-nistp521-cert-v01@openssh.com",
    "sk-ssh-ed25519-cert-v01@openssh.com",
    "sk-ecdsa-sha2-nistp256-cert-v01@openssh.com",
}


class AdminUserError(RuntimeError):
    def __init__(self, message: str, diagnostics: list[str] | None = None) -> None:
        super().__init__(message)
        self.diagnostics = diagnostics or ["getent passwd USER", "id USER", "ls -ld ~USER/.ssh ~USER/.ssh/authorized_keys"]


@dataclass(frozen=True)
class AdminUserDiscovery:
    username: str
    exists: bool
    uid: int | None
    home: Path | None
    shell: str
    sudo_member: bool
    ssh_dir_exists: bool
    authorized_keys_exists: bool
    ssh_dir_mode_ok: bool
    authorized_keys_mode_ok: bool
    key_fingerprints: list[str]
    password_locked: bool = False
    ssh_dir_owner_ok: bool = True
    authorized_keys_owner_ok: bool = True
    gid: int | None = None
    uid_min: int = DEFAULT_UID_MIN
    home_mode_ok: bool = True
    home_owner_ok: bool = True
    local_password_status: str = ""

    @property
    def normal_login_user(self) -> bool:
        return (
            self.exists
            and self.uid is not None
            and self.uid >= self.uid_min
            and self.username != "root"
            and bool(self.home)
            and self.shell not in {"", "/usr/sbin/nologin", "/bin/false", "/sbin/nologin"}
        )

    @property
    def usable(self) -> bool:
        return (
            self.normal_login_user
            and self.sudo_member
            and self.ssh_dir_exists
            and self.authorized_keys_exists
            and self.ssh_dir_mode_ok
            and self.authorized_keys_mode_ok
            and self.ssh_dir_owner_ok
            and self.authorized_keys_owner_ok
            and self.home_mode_ok
            and self.home_owner_ok
            and bool(self.key_fingerprints)
        )

    @property
    def local_password_usable(self) -> bool:
        return self.local_password_status == "P"


@dataclass(frozen=True)
class AdminUserPlan:
    username: str
    create_user: bool
    public_key: str | None = None
    fingerprint: str = ""
    sudo_mode: str = SUDO_MODE_PASSWORD_REQUIRED
    local_password_policy: str = ""


def validate_username(username: str) -> str:
    value = username.strip()
    if value == "root":
        raise AdminUserError("root cannot be used as the managed administrative user.")
    if not USERNAME_RE.match(value):
        raise AdminUserError("Invalid username. Use a lower-case Linux username without spaces.")
    return value


def validate_public_key(public_key: str) -> str:
    line = public_key.strip()
    key_type, key_body = public_key_fields(line)
    try:
        base64.b64decode(key_body.encode("ascii"), validate=True)
    except Exception as exc:  # noqa: BLE001 - hide parser internals from user.
        raise AdminUserError("SSH public key body is not valid base64.") from exc
    return line


def public_key_fields(public_key: str) -> tuple[str, str]:
    try:
        parts = shlex.split(public_key, comments=False, posix=True)
    except ValueError as exc:
        raise AdminUserError("SSH public key options are malformed.") from exc
    for index, value in enumerate(parts):
        if value in SUPPORTED_KEY_TYPES:
            if index + 1 >= len(parts):
                raise AdminUserError("SSH public key is incomplete.")
            return value, parts[index + 1]
    first = parts[0] if parts else "missing"
    raise AdminUserError(f"Unsupported SSH public key type: {first}")


def fingerprint_public_key(public_key: str) -> str:
    line = validate_public_key(public_key)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as handle:
        handle.write(line + "\n")
        tmp_name = handle.name
    try:
        result = run_command(["ssh-keygen", "-l", "-f", tmp_name], timeout=10)
    finally:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
    if not result.ok:
        raise AdminUserError("OpenSSH public key validation failed.", ["ssh-keygen -l -f <public-key-file>"])
    parts = result.stdout.split()
    if len(parts) < 2 or not parts[1].startswith("SHA256:"):
        raise AdminUserError("Could not parse public key fingerprint from ssh-keygen output.")
    return parts[1]


def discover_admin_user(username: str) -> AdminUserDiscovery:
    user = validate_username(username)
    uid_min = read_uid_min()
    try:
        entry = pwd.getpwnam(user)
    except KeyError:
        return AdminUserDiscovery(user, False, None, None, "", False, False, False, False, False, [], gid=None, uid_min=uid_min)
    groups = run_command(["id", "-nG", user], timeout=5)
    sudo_member = groups.ok and "sudo" in groups.stdout.split()
    password_status = account_password_status(user)
    home = Path(entry.pw_dir)
    ssh_dir = home / ".ssh"
    keys = ssh_dir / AUTHORIZED_KEYS_NAME
    fingerprints = authorized_key_fingerprints(keys) if keys.exists() else []
    ssh_owner_ok = owner_ok(ssh_dir, entry.pw_uid, entry.pw_gid) if ssh_dir.exists() else False
    keys_owner_ok = owner_ok(keys, entry.pw_uid, entry.pw_gid) if keys.exists() else False
    return AdminUserDiscovery(
        username=user,
        exists=True,
        uid=entry.pw_uid,
        home=home,
        shell=entry.pw_shell,
        sudo_member=sudo_member,
        ssh_dir_exists=ssh_dir.is_dir(),
        authorized_keys_exists=keys.is_file(),
        ssh_dir_mode_ok=has_mode(ssh_dir, 0o700) if ssh_dir.exists() else False,
        authorized_keys_mode_ok=has_mode(keys, 0o600) if keys.exists() else False,
        key_fingerprints=fingerprints,
        password_locked=password_status in {"L", "LK", "NP"},
        ssh_dir_owner_ok=ssh_owner_ok,
        authorized_keys_owner_ok=keys_owner_ok,
        gid=entry.pw_gid,
        uid_min=uid_min,
        home_mode_ok=has_mode(home, 0o700) if home.exists() else False,
        home_owner_ok=owner_ok(home, entry.pw_uid, entry.pw_gid) if home.exists() else False,
        local_password_status=password_status,
    )


def authorized_key_fingerprints(path: Path) -> list[str]:
    fingerprints: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        try:
            fingerprints.append(fingerprint_public_key(stripped))
        except AdminUserError:
            continue
    return fingerprints


def render_authorized_keys(public_key: str) -> str:
    return validate_public_key(public_key) + "\n"


def owner_ok(path: Path, uid: int, gid: int) -> bool:
    try:
        stat_result = path.stat()
        return stat_result.st_uid == uid and stat_result.st_gid == gid
    except OSError:
        return False


def key_identity(public_key: str) -> tuple[str, str]:
    return public_key_fields(validate_public_key(public_key))


def read_uid_min(path: Path | None = None) -> int:
    source = path or LOGIN_DEFS
    try:
        for raw in source.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = raw.split("#", 1)[0].strip()
            parts = line.split()
            if len(parts) >= 2 and parts[0] == "UID_MIN" and parts[1].isdigit():
                value = int(parts[1])
                return value if value > 0 else DEFAULT_UID_MIN
    except OSError:
        pass
    return DEFAULT_UID_MIN


def merge_authorized_keys(existing_content: str, public_key: str) -> str:
    candidate = validate_public_key(public_key)
    candidate_identity = key_identity(candidate)
    lines = existing_content.splitlines()
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        try:
            if key_identity(stripped) == candidate_identity:
                return existing_content if existing_content.endswith("\n") else existing_content + "\n"
        except AdminUserError:
            continue
    output = existing_content
    if output and not output.endswith("\n"):
        output += "\n"
    output += candidate + "\n"
    return output


def setup_password_interactively(username: str) -> None:
    print(f"Set a local password for {username} using the system passwd tool.")
    print("vps-bootstrap will not read, log, or store this password.")
    completed = subprocess.run(["passwd", username], check=False)  # noqa: S603 - interactive OS tool, terminal inherited intentionally.
    if completed.returncode != 0:
        raise AdminUserError(f"Password setup for {username} was cancelled or failed.")
    if account_password_status(username) != "P":
        raise AdminUserError(f"Password setup for {username} completed but a usable local password was not verified.")


def account_password_status(username: str) -> str:
    result = run_command(["passwd", "-S", username], timeout=10)
    parts = result.stdout.split()
    return parts[1].upper() if result.ok and len(parts) >= 2 else ""


def lock_local_password(username: str) -> None:
    result = run_command(["passwd", "-l", username], timeout=15)
    if not result.ok:
        raise AdminUserError(f"Failed to lock the local password for {username}: {result.stderr or result.stdout}")
    if account_password_status(username) != "L":
        raise AdminUserError(f"Local password lock verification failed for {username}.")


def normalize_sudo_mode(value: str) -> str:
    if value not in {SUDO_MODE_PASSWORD_REQUIRED, SUDO_MODE_NOPASSWD}:
        raise AdminUserError(f"Unsupported sudo authentication mode: {value}")
    return value


def render_managed_sudoers(username: str) -> str:
    user = validate_username(username)
    return f"{SUDOERS_HEADER}\n{user} ALL=(ALL:ALL) NOPASSWD: ALL\n"


def managed_sudoers_is_owned() -> bool:
    try:
        return MANAGED_SUDOERS.read_text(encoding="utf-8").splitlines()[0] == SUDOERS_HEADER
    except (OSError, IndexError):
        return False


def validate_sudoers_configuration() -> None:
    result = run_command(["visudo", "-cf", str(SUDOERS_FILE)], timeout=15)
    if not result.ok:
        raise AdminUserError(f"sudoers validation failed: {result.stderr or result.stdout}", [f"visudo -cf {SUDOERS_FILE}"])


def root_owned(path: Path) -> bool:
    try:
        stat_result = path.stat()
        return stat_result.st_uid == 0 and stat_result.st_gid == 0
    except OSError:
        return False


def backup_managed_sudoers() -> Path | None:
    if not MANAGED_SUDOERS.exists():
        return None
    backup = MANAGED_SUDOERS.with_name(f"{MANAGED_SUDOERS.name}.bak-{time.time_ns()}")
    shutil.copy2(MANAGED_SUDOERS, backup)
    chown_root_if_possible(backup)
    os.chmod(backup, 0o600)
    return backup


def restore_managed_sudoers(backup: Path | None, existed: bool) -> None:
    if backup:
        write_atomic(MANAGED_SUDOERS, backup.read_text(encoding="utf-8"), 0o440)
        chown_root_if_possible(MANAGED_SUDOERS)
    elif not existed and MANAGED_SUDOERS.exists():
        MANAGED_SUDOERS.unlink()


def configure_sudo_policy(username: str, sudo_mode: str) -> None:
    mode = normalize_sudo_mode(sudo_mode)
    existed = MANAGED_SUDOERS.exists()
    if existed and not managed_sudoers_is_owned():
        raise AdminUserError(f"Refusing to replace unmanaged sudoers file: {MANAGED_SUDOERS}")
    backup = backup_managed_sudoers()
    try:
        if mode == SUDO_MODE_NOPASSWD:
            write_atomic(MANAGED_SUDOERS, render_managed_sudoers(username), 0o440)
            chown_root_if_possible(MANAGED_SUDOERS)
        elif MANAGED_SUDOERS.exists():
            MANAGED_SUDOERS.unlink()
        validate_sudoers_configuration()
    except (Exception, KeyboardInterrupt) as original_error:
        try:
            restore_managed_sudoers(backup, existed)
            validate_sudoers_configuration()
        except (Exception, KeyboardInterrupt) as rollback_error:
            raise AdminUserError(
                f"CRITICAL: sudoers policy failed and the previous managed policy could not be restored: {rollback_error}"
            ) from original_error
        raise
    finally:
        if backup and backup.exists():
            backup.unlink()


def verify_sudo_policy(username: str, sudo_mode: str) -> bool:
    try:
        mode = normalize_sudo_mode(sudo_mode)
    except AdminUserError:
        return False
    if mode == SUDO_MODE_PASSWORD_REQUIRED:
        if MANAGED_SUDOERS.exists():
            return False
    else:
        if not MANAGED_SUDOERS.is_file():
            return False
        try:
            content_matches = MANAGED_SUDOERS.read_text(encoding="utf-8") == render_managed_sudoers(username)
        except OSError:
            return False
        if not content_matches or not has_mode(MANAGED_SUDOERS, 0o440) or not root_owned(MANAGED_SUDOERS):
            return False
    try:
        validate_sudoers_configuration()
    except AdminUserError:
        return False
    return True


def ensure_admin_home_permissions(username: str) -> tuple[Path, int, int]:
    entry = pwd.getpwnam(username)
    if entry.pw_uid < read_uid_min():
        raise AdminUserError(f"Refusing to manage system account with UID {entry.pw_uid}: {username}")
    home = Path(entry.pw_dir)
    if not home.is_dir():
        raise AdminUserError(f"Administrative user home directory is missing: {home}")
    os.chmod(home, 0o700)
    chown = run_command(["chown", f"{entry.pw_uid}:{entry.pw_gid}", str(home)], timeout=30)
    if not chown.ok:
        raise AdminUserError(f"Failed to set ownership for {home}: {chown.stderr or chown.stdout}")
    return home, entry.pw_uid, entry.pw_gid


def sudo_validation_commands(sudo_mode: str) -> list[str]:
    if normalize_sudo_mode(sudo_mode) == SUDO_MODE_NOPASSWD:
        return [
            "sudo -k",
            "sudo -n true",
            "sudo -n whoami  # must print: root",
        ]
    return [
        "sudo -k",
        "sudo -n true  # EXPECTED TO FAIL before authentication",
        "sudo -v  # enter the normal sudo password",
        "sudo -n true",
        "echo $?  # must print: 0",
    ]


def print_sudo_validation_instructions(
    sudo_mode: str,
    heading: str = "Then verify the selected sudo policy in that second session:",
) -> None:
    normalized = normalize_sudo_mode(sudo_mode)
    print(heading)
    if normalized == SUDO_MODE_PASSWORD_REQUIRED:
        print("  The first 'sudo -n true' is EXPECTED TO FAIL; this proves sudo requires authentication.")
        print("  That expected failure is part of validation, not a bootstrap failure.")
        print("  After 'sudo -v', the second non-interactive check must succeed with exit code 0.")
    else:
        print("  All commands must succeed non-interactively; 'sudo -n whoami' must print root.")
    for command in sudo_validation_commands(normalized):
        print(f"  {command}")


def ensure_existing_password_for_sudo(discovery: AdminUserDiscovery, sudo_mode: str) -> str:
    if normalize_sudo_mode(sudo_mode) != SUDO_MODE_PASSWORD_REQUIRED:
        return "configured" if discovery.local_password_usable else "locked" if discovery.password_locked else "unknown"
    if discovery.local_password_usable:
        return "configured"
    print(f"[WARN] {discovery.username} does not have a verified usable local password.")
    if not confirm("Set a local password with the system passwd tool before enabling password-required sudo? [y/N]: "):
        raise AdminUserError(
            "Password-required sudo cannot be enabled until the existing admin has a verified local password."
        )
    setup_password_interactively(discovery.username)
    return "configured"


def apply_admin_user_plan(plan: AdminUserPlan, ssh_host: str = "SERVER_IP") -> dict:
    username = validate_username(plan.username)
    sudo_mode = normalize_sudo_mode(plan.sudo_mode)
    fingerprint = plan.fingerprint or (fingerprint_public_key(plan.public_key or "") if plan.public_key else "")
    if plan.create_user:
        result = run_command(["useradd", "--create-home", "--shell", "/bin/bash", username], timeout=30)
        if not result.ok and "already exists" not in (result.stderr + result.stdout).lower():
            raise AdminUserError(f"Failed to create user {username}: {result.stderr or result.stdout}")
        local_policy = plan.local_password_policy or "set"
        if local_policy == "set":
            setup_password_interactively(username)
            local_password_status = "configured"
        elif local_policy == "locked" and sudo_mode == SUDO_MODE_NOPASSWD:
            lock_local_password(username)
            local_password_status = "locked"
            print("[WARN] Console password login is unavailable for this admin; preserve provider recovery access.")
        else:
            raise AdminUserError(f"Unsupported local password policy for a new admin: {local_policy}")
    else:
        existing_user = discover_admin_user(username)
        if not existing_user.normal_login_user:
            raise AdminUserError(f"Existing account is not a normal non-root login user: {username}")
        local_password_status = ensure_existing_password_for_sudo(existing_user, sudo_mode)
    usermod = run_command(["usermod", "-aG", "sudo", username], timeout=30)
    if not usermod.ok:
        raise AdminUserError(f"Failed to add {username} to sudo group: {usermod.stderr or usermod.stdout}")
    home, uid, gid = ensure_admin_home_permissions(username)
    if plan.public_key:
        ssh_dir = home / ".ssh"
        ssh_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(ssh_dir, 0o700)
        keys_path = ssh_dir / AUTHORIZED_KEYS_NAME
        existing = keys_path.read_text(encoding="utf-8", errors="ignore") if keys_path.exists() else ""
        write_atomic(keys_path, merge_authorized_keys(existing, plan.public_key), 0o600)
        chown = run_command(["chown", f"{uid}:{gid}", str(ssh_dir), str(keys_path)], timeout=30)
        if not chown.ok:
            raise AdminUserError(f"Failed to set ownership for {ssh_dir}: {chown.stderr or chown.stdout}")
    configure_sudo_policy(username, sudo_mode)
    print(f"Admin user public key fingerprint: {fingerprint}")
    print("Open a SECOND terminal and verify publickey-only login:")
    for line in admin_second_session_instructions(username, ssh_host):
        print(f"  {line}")
    print_sudo_validation_instructions(sudo_mode)
    if not confirm("Did publickey-only login AND the sudo checks behave exactly as described? [y/N]: "):
        raise AdminUserError("Admin user was configured but second-session sudo validation was not confirmed.")
    return {
        "mode": "managed",
        "username": username,
        "fingerprint": fingerprint,
        "validated": True,
        "sudo_mode": sudo_mode,
        "sudo_validated": True,
        "local_password_status": local_password_status,
        "local_password_usable": local_password_status == "configured",
    }


def confirm_existing_admin_user(
    discovery: AdminUserDiscovery,
    ssh_host: str = "SERVER_IP",
    sudo_mode: str = SUDO_MODE_PASSWORD_REQUIRED,
) -> dict:
    sudo_mode = normalize_sudo_mode(sudo_mode)
    if not discovery.usable:
        raise AdminUserError(f"Existing user is not yet a suitable admin user: {discovery.username}")
    fingerprint = discovery.key_fingerprints[0]
    ensure_admin_home_permissions(discovery.username)
    local_status = ensure_existing_password_for_sudo(discovery, sudo_mode)
    configure_sudo_policy(discovery.username, sudo_mode)
    print(f"Existing admin user public key fingerprint: {fingerprint}")
    print("Open a SECOND terminal and verify publickey-only login:")
    for line in admin_second_session_instructions(discovery.username, ssh_host):
        print(f"  {line}")
    print_sudo_validation_instructions(sudo_mode)
    if not confirm("Did publickey-only login AND the sudo checks behave exactly as described? [y/N]: "):
        raise AdminUserError("Existing admin user second-session sudo validation was not confirmed.")
    return {
        "mode": "managed",
        "username": discovery.username,
        "fingerprint": fingerprint,
        "validated": True,
        "sudo_mode": sudo_mode,
        "sudo_validated": True,
        "local_password_status": local_status,
        "local_password_usable": local_status == "configured",
    }


def admin_second_session_command(username: str, ssh_host: str = "SERVER_IP", port: int | None = None) -> str:
    selected_port = port if port is not None else current_ssh_port()
    target = f"{username}@{format_ssh_host(ssh_host)}"
    return publickey_only_ssh_command(target, selected_port)


def admin_second_session_instructions(
    username: str,
    ssh_host: str = "SERVER_IP",
    port: int | None = None,
) -> list[str]:
    selected_port = port if port is not None else current_ssh_port()
    target = f"{username}@{format_ssh_host(ssh_host)}"
    return publickey_only_ssh_instruction_lines(target, selected_port)


def current_ssh_port() -> int:
    try:
        from app.ssh_hardening import discover_ssh

        discovery = discover_ssh()
        ports = sorted(discovery.actual_ssh_listeners or discovery.configured_ports or {22})
        return ports[0]
    except Exception:
        return 22


def verify_admin_user_state(data: dict) -> bool:
    if data.get("mode") == "skipped":
        return True
    username = data.get("username")
    fingerprint = data.get("fingerprint")
    if not username or not fingerprint or not data.get("validated") or not data.get("sudo_validated", data.get("validated")):
        return False
    discovery = discover_admin_user(str(username))
    if not discovery.usable or str(fingerprint) not in discovery.key_fingerprints:
        return False
    sudo_mode = str(data.get("sudo_mode", SUDO_MODE_PASSWORD_REQUIRED))
    if not verify_sudo_policy(str(username), sudo_mode):
        return False
    expected_local = data.get("local_password_status")
    if expected_local == "configured" and not discovery.local_password_usable:
        return False
    if expected_local == "locked" and not discovery.password_locked:
        return False
    return True


def choose_sudo_mode(username: str) -> str:
    print(f"Configure sudo authentication for {username}:")
    print("[1] Require user password for sudo (recommended)")
    print("[2] Passwordless sudo for this admin only")
    choice = input("Select option [1]: ").strip() or "1"
    if choice == "1":
        return SUDO_MODE_PASSWORD_REQUIRED
    if choice == "2":
        return SUDO_MODE_NOPASSWD
    raise AdminUserError("Unknown sudo authentication option.")


def choose_new_user_local_password_policy(sudo_mode: str) -> str:
    if sudo_mode == SUDO_MODE_PASSWORD_REQUIRED:
        return "set"
    print("Configure a local password for console/recovery login?")
    print("[1] Set a local password (recommended)")
    print("[2] Keep the local password locked; SSH key only")
    choice = input("Select option [1]: ").strip() or "1"
    if choice == "1":
        return "set"
    if choice == "2":
        return "locked"
    raise AdminUserError("Unknown local password option.")


def ensure_admin_user_from_state(data: dict, force_reconfigure: bool = False) -> dict:
    if data and data.get("mode") == "managed" and not force_reconfigure and verify_admin_user_state(data):
        return data
    print("Administrative user setup")
    print("[1] Create a new non-root administrative user (recommended)")
    print("[2] Use an existing suitable non-root user")
    print("[3] Skip admin user setup")
    choice = input("Select option [1]: ").strip() or "1"
    if choice == "3":
        return {"mode": "skipped", "reason": "user skipped admin user setup"}
    username = validate_username(input("Admin username: ").strip())
    exists = discover_admin_user(username).exists
    discovery = discover_admin_user(username)
    create_user = choice == "1"
    if create_user and exists:
        raise AdminUserError(f"User already exists: {username}")
    if choice == "2" and not exists:
        raise AdminUserError(f"Existing user was not found: {username}")
    if choice == "2" and not discovery.normal_login_user:
        raise AdminUserError(f"Existing account is not a normal non-root login user: {username}")
    sudo_mode = choose_sudo_mode(username)
    local_password_policy = choose_new_user_local_password_policy(sudo_mode) if create_user else "unchanged"
    host = server_address_from_ssh_connection(os.environ.get("SSH_CONNECTION", "")) or "SERVER_IP"
    if choice == "2" and discovery.usable and confirm("Use existing authorized_keys for this user? [Y/n]: ", default=True):
        return confirm_existing_admin_user(discovery, host, sudo_mode)
    public_key = input("Paste SSH PUBLIC key for this admin user: ").strip()
    fingerprint = fingerprint_public_key(public_key)
    return apply_admin_user_plan(AdminUserPlan(username, create_user, public_key, fingerprint, sudo_mode, local_password_policy), host)


def install_state_from_discovery(discovery: AdminUserDiscovery, fingerprint: str) -> dict:
    local_status = "configured" if discovery.local_password_usable else "locked" if discovery.password_locked else "unknown"
    return {
        "mode": "managed",
        "username": discovery.username,
        "fingerprint": fingerprint,
        "validated": discovery.usable,
        "sudo_mode": SUDO_MODE_PASSWORD_REQUIRED,
        "sudo_validated": discovery.usable,
        "local_password_status": local_status,
        "local_password_usable": discovery.local_password_usable,
    }
