from __future__ import annotations

import os
import ipaddress
import re
import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path
from time import monotonic, sleep

from app.command import run_command
from app.filesystem import write_atomic


MANAGED_JAIL = Path(os.environ.get("VPS_BOOTSTRAP_FAIL2BAN_JAIL", "/etc/fail2ban/jail.d/10-vps-bootstrap-sshd.local"))
FAIL2BAN_CONFIG_ROOT = Path(os.environ.get("VPS_BOOTSTRAP_FAIL2BAN_CONFIG_ROOT", "/etc/fail2ban"))
DEFAULT_MAXRETRY = 5
DEFAULT_FINDTIME = "10m"
DEFAULT_BANTIME = "1h"
FAIL2BAN_READY_TIMEOUT_SECONDS = 15.0
FAIL2BAN_READY_INTERVAL_SECONDS = 0.25


class Fail2banError(RuntimeError):
    def __init__(self, message: str, diagnostics: list[str] | None = None) -> None:
        super().__init__(message)
        self.diagnostics = diagnostics or ["fail2ban-client status", "fail2ban-client status sshd", "systemctl status fail2ban --no-pager -l"]


@dataclass(frozen=True)
class Fail2banSettings:
    ports: list[int]
    maxretry: int = DEFAULT_MAXRETRY
    findtime: str = DEFAULT_FINDTIME
    bantime: str = DEFAULT_BANTIME
    ignoreip: list[str] = field(default_factory=list)
    enabled: bool = True


def validate_duration(value: str) -> str:
    text = value.strip()
    if not re.match(r"^\d+[smhdw]?$", text):
        raise Fail2banError(f"Invalid Fail2ban duration: {value}")
    return text


def validate_settings(settings: Fail2banSettings) -> None:
    if settings.maxretry < 1 or settings.maxretry > 50:
        raise Fail2banError("Fail2ban maxretry must be between 1 and 50.")
    validate_duration(settings.findtime)
    validate_duration(settings.bantime)
    for port in settings.ports:
        if port < 1 or port > 65535:
            raise Fail2banError(f"Invalid SSH port for Fail2ban: {port}")
    for entry in settings.ignoreip:
        validate_ignoreip_entry(entry)


def validate_ignoreip_entry(value: str) -> str:
    text = value.strip()
    try:
        ipaddress.ip_network(text, strict=False)
    except ValueError as exc:
        raise Fail2banError(f"Invalid ignoreip IP/CIDR entry: {value}") from exc
    return text


def render_jail(settings: Fail2banSettings) -> str:
    validate_settings(settings)
    lines = [
        "# Managed by vps-bootstrap. Do not edit this file directly.",
        "[sshd]",
        f"enabled = {'true' if settings.enabled else 'false'}",
        "backend = systemd",
        "port = " + ",".join(str(port) for port in sorted(settings.ports)),
        f"maxretry = {settings.maxretry}",
        f"findtime = {settings.findtime}",
        f"bantime = {settings.bantime}",
    ]
    if settings.ignoreip:
        lines.append("ignoreip = " + " ".join(settings.ignoreip))
    return "\n".join(lines) + "\n"


def parse_managed_jail(content: str) -> Fail2banSettings:
    values: dict[str, str] = {}
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip().lower()] = value.strip()
    ports = [int(part) for part in re.split(r"[,\s]+", values.get("port", "")) if part.isdigit()]
    ignoreip = values.get("ignoreip", "").split() if values.get("ignoreip") else []
    return Fail2banSettings(
        ports=ports,
        maxretry=int(values.get("maxretry", DEFAULT_MAXRETRY)),
        findtime=values.get("findtime", DEFAULT_FINDTIME),
        bantime=values.get("bantime", DEFAULT_BANTIME),
        ignoreip=ignoreip,
        enabled=values.get("enabled", "true").lower() == "true",
    )


def current_ssh_ports() -> list[int]:
    from app.ssh_hardening import discover_ssh

    discovery = discover_ssh()
    return sorted(discovery.actual_ssh_listeners or discovery.configured_ports or {22})


def install_fail2ban_if_missing() -> None:
    if shutil.which("fail2ban-client"):
        return
    result = run_command(["apt-get", "install", "-y", "fail2ban"], timeout=120)
    if not result.ok:
        raise Fail2banError(f"Failed to install fail2ban: {result.stderr or result.stdout}")


def apply_settings(settings: Fail2banSettings) -> None:
    backup = backup_jail("apply")
    existed = MANAGED_JAIL.exists()
    runtime_attempted = False
    write_atomic(MANAGED_JAIL, render_jail(settings), 0o600)
    try:
        validate_fail2ban_configuration()
        runtime_attempted = True
        result = run_command(["systemctl", "enable", "--now", "fail2ban"], timeout=60)
        if not result.ok:
            raise Fail2banError(f"Failed to enable Fail2ban: {result.stderr or result.stdout}")
        restart = run_command(["systemctl", "restart", "fail2ban"], timeout=60)
        if not restart.ok:
            raise Fail2banError(f"Failed to restart Fail2ban: {restart.stderr or restart.stdout}")
        wait_for_fail2ban_ready()
    except (Exception, KeyboardInterrupt) as original_error:
        try:
            restore_jail_backup(backup, existed)
            if runtime_attempted:
                validate_fail2ban_configuration()
                restart = run_command(["systemctl", "restart", "fail2ban"], timeout=60)
                if not restart.ok:
                    raise Fail2banError(f"restored Fail2ban restart failed: {restart.stderr or restart.stdout}")
                if existed:
                    wait_for_fail2ban_ready()
        except (Exception, KeyboardInterrupt) as rollback_error:
            raise Fail2banError(
                f"CRITICAL: Fail2ban apply failed and runtime rollback could not be verified: {rollback_error}"
            ) from original_error
        raise


def validate_fail2ban_configuration() -> None:
    result = run_command(["fail2ban-client", "-t"], timeout=30)
    if not result.ok:
        raise Fail2banError(f"Fail2ban configuration test failed: {result.stderr or result.stdout}")


def wait_for_fail2ban_ready(
    timeout_seconds: float | None = None,
    interval_seconds: float | None = None,
    *,
    raise_on_timeout: bool = True,
) -> bool:
    timeout = FAIL2BAN_READY_TIMEOUT_SECONDS if timeout_seconds is None else max(0.0, timeout_seconds)
    interval = FAIL2BAN_READY_INTERVAL_SECONDS if interval_seconds is None else max(0.01, interval_seconds)
    deadline = monotonic() + timeout

    while True:
        service = run_command(["systemctl", "is-active", "fail2ban"], timeout=10)
        if service.ok and service.stdout.strip() == "active":
            jail = run_command(["fail2ban-client", "status", "sshd"], timeout=10)
            if jail.ok:
                return True

        remaining = deadline - monotonic()
        if remaining <= 0:
            if raise_on_timeout:
                raise Fail2banError(f"Fail2ban sshd jail did not become ready within {timeout:g} seconds.")
            return False
        sleep(min(interval, remaining))


def ensure_fail2ban_from_state(data: dict, force_reconfigure: bool = False) -> dict:
    if data and data.get("mode") == "managed" and not force_reconfigure and verify_fail2ban_state(data):
        return data
    print("Configure Fail2ban protection for SSH?")
    print("[1] Recommended settings (default)")
    print("[2] Customize")
    print("[3] Skip Fail2ban")
    if force_reconfigure and MANAGED_JAIL.exists():
        print("[4] Disable managed SSH jail")
    choice = input("Select option [1]: ").strip() or "1"
    if choice == "3":
        return {"mode": "skipped", "reason": "user skipped Fail2ban"}
    if choice == "4" and force_reconfigure:
        if MANAGED_JAIL.exists():
            MANAGED_JAIL.unlink()
        run_command(["systemctl", "restart", "fail2ban"], timeout=60)
        return {"mode": "skipped", "reason": "managed Fail2ban sshd jail disabled"}
    ports = current_ssh_ports()
    settings = recommended_settings(ports) if choice == "1" else customize_settings(ports)
    print("Fail2ban sshd settings:")
    print(f"  ports: {settings.ports}")
    print(f"  maxretry: {settings.maxretry}")
    print(f"  findtime: {settings.findtime}")
    print(f"  bantime: {settings.bantime}")
    print(f"  ignoreip: {settings.ignoreip}")
    from app.ssh_hardening import confirm

    if not confirm("Apply managed Fail2ban sshd jail? [Y/n]: ", default=True):
        return {"mode": "skipped", "reason": "user did not confirm Fail2ban"}
    install_fail2ban_if_missing()
    apply_settings(settings)
    state = settings_state(settings)
    if not verify_fail2ban_state(state):
        raise Fail2banError("Managed Fail2ban verification failed after apply.")
    return state


def recommended_settings(ports: list[int]) -> Fail2banSettings:
    return Fail2banSettings(ports=ports)


def customize_settings(ports: list[int]) -> Fail2banSettings:
    maxretry_raw = input("maxretry [5]: ").strip() or str(DEFAULT_MAXRETRY)
    if not maxretry_raw.isdigit():
        raise Fail2banError("maxretry must be numeric.")
    findtime = validate_duration(input("findtime [10m]: ").strip() or DEFAULT_FINDTIME)
    bantime = validate_duration(input("bantime [1h]: ").strip() or DEFAULT_BANTIME)
    ignoreip_raw = input("trusted IP/CIDR entries for ignoreip, space-separated [none]: ").strip()
    ignoreip = [validate_ignoreip_entry(item) for item in ignoreip_raw.split()]
    return Fail2banSettings(ports=ports, maxretry=int(maxretry_raw), findtime=findtime, bantime=bantime, ignoreip=ignoreip)


def settings_state(settings: Fail2banSettings) -> dict:
    return {
        "mode": "managed",
        "ports": sorted(settings.ports),
        "maxretry": settings.maxretry,
        "findtime": settings.findtime,
        "bantime": settings.bantime,
        "ignoreip": list(settings.ignoreip),
    }


def verify_fail2ban_state(data: dict) -> bool:
    if data.get("mode") == "skipped":
        return True
    if data.get("mode") != "managed" or not MANAGED_JAIL.exists():
        return False
    expected_ports = {int(port) for port in data.get("ports", [])}
    try:
        settings = parse_managed_jail(MANAGED_JAIL.read_text(encoding="utf-8"))
    except Exception:
        return False
    config_test = run_command(["fail2ban-client", "-t"], timeout=30)
    if not config_test.ok or conflicting_sshd_port_overrides(expected_ports):
        return False
    if not wait_for_fail2ban_ready(raise_on_timeout=False):
        return False
    return expected_ports == set(settings.ports) == set(current_ssh_ports())


def managed_fail2ban_exists() -> bool:
    if not MANAGED_JAIL.is_file():
        return False
    try:
        settings = parse_managed_jail(MANAGED_JAIL.read_text(encoding="utf-8"))
        validate_settings(settings)
    except (OSError, ValueError, Fail2banError):
        return False
    return settings.enabled and bool(settings.ports)


def backup_jail(purpose: str = "operation") -> Path | None:
    if not MANAGED_JAIL.exists():
        return None
    safe_purpose = re.sub(r"[^a-z0-9-]", "-", purpose.lower())
    backup = MANAGED_JAIL.with_name(f"{MANAGED_JAIL.name}.bak-{safe_purpose}-{time.time_ns()}")
    shutil.copy2(MANAGED_JAIL, backup)
    os.chmod(backup, 0o600)
    return backup


def restore_jail_backup(backup: Path | None, existed: bool = True) -> None:
    if backup:
        shutil.copy2(backup, MANAGED_JAIL)
        os.chmod(MANAGED_JAIL, 0o600)
    elif not existed and MANAGED_JAIL.exists():
        MANAGED_JAIL.unlink()


def prepare_ssh_migration(old_ports: set[int], transition_ports: set[int]) -> dict:
    if not managed_fail2ban_exists():
        return {"managed": False}
    settings = parse_managed_jail(MANAGED_JAIL.read_text(encoding="utf-8"))
    backup = backup_jail("transaction")
    transition_settings = Fail2banSettings(sorted(transition_ports), settings.maxretry, settings.findtime, settings.bantime, settings.ignoreip)
    apply_settings(transition_settings)
    return {
        "managed": True,
        "backup": str(backup) if backup else None,
        "old_ports": sorted(old_ports),
        "original_state": settings_state(settings),
        "transition_state": settings_state(transition_settings),
    }


def finalize_ssh_migration(final_ports: set[int], metadata: dict) -> dict | None:
    if not metadata.get("managed"):
        return None
    settings = parse_managed_jail(MANAGED_JAIL.read_text(encoding="utf-8"))
    final_settings = Fail2banSettings(sorted(final_ports), settings.maxretry, settings.findtime, settings.bantime, settings.ignoreip)
    apply_settings(final_settings)
    final_state = settings_state(final_settings)
    metadata["final_state"] = final_state
    return final_state


def rollback_ssh_migration(metadata: dict) -> None:
    if not metadata.get("managed"):
        return
    backup = trusted_transaction_backup(metadata.get("backup"))
    original_state = metadata.get("original_state")
    if not isinstance(original_state, dict):
        raise Fail2banError("Fail2ban rollback metadata is missing the original managed state.")
    restore_jail_backup(backup, existed=True)
    validate_fail2ban_configuration()
    result = run_command(["systemctl", "restart", "fail2ban"], timeout=60)
    if not result.ok:
        raise Fail2banError(f"Failed to restart Fail2ban during rollback: {result.stderr or result.stdout}")
    if not verify_fail2ban_state(original_state):
        raise Fail2banError("CRITICAL: restored Fail2ban SSH jail did not pass verification.")
    metadata["rollback_state"] = original_state


def trusted_transaction_backup(value: object) -> Path:
    if not value:
        raise Fail2banError("Fail2ban transaction backup metadata is missing.")
    backup = Path(str(value))
    expected_prefix = f"{MANAGED_JAIL.name}.bak-transaction-"
    try:
        trusted_parent = backup.parent.resolve() == MANAGED_JAIL.parent.resolve()
    except OSError as exc:
        raise Fail2banError(f"Cannot validate Fail2ban transaction backup path: {exc}") from exc
    if not backup.is_absolute() or not trusted_parent or not backup.name.startswith(expected_prefix):
        raise Fail2banError(f"Untrusted Fail2ban transaction backup path: {backup}")
    if not backup.is_file():
        raise Fail2banError(f"Fail2ban transaction backup is missing: {backup}")
    return backup


def fail2ban_service_and_jail_active() -> bool:
    return wait_for_fail2ban_ready(raise_on_timeout=False)


def conflicting_sshd_port_overrides(expected_ports: set[int]) -> list[str]:
    conflicts: list[str] = []
    candidates: list[Path] = []
    jail_local = FAIL2BAN_CONFIG_ROOT / "jail.local"
    if jail_local.is_file():
        candidates.append(jail_local)
    jail_d = FAIL2BAN_CONFIG_ROOT / "jail.d"
    if jail_d.is_dir():
        candidates.extend(sorted(path for path in jail_d.iterdir() if path.suffix in {".conf", ".local"}))
    try:
        managed_resolved = MANAGED_JAIL.resolve()
    except OSError:
        managed_resolved = MANAGED_JAIL
    for path in candidates:
        try:
            if path.resolve() == managed_resolved:
                continue
            configured = sshd_ports_from_config(path.read_text(encoding="utf-8", errors="ignore"))
        except OSError:
            conflicts.append(str(path))
            continue
        if configured is not None and configured != expected_ports:
            conflicts.append(str(path))
    return conflicts


def sshd_ports_from_config(content: str) -> set[int] | None:
    section = ""
    found: set[int] | None = None
    for raw in content.splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ";")):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip().lower()
            continue
        if section != "sshd" or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key.strip().lower() != "port":
            continue
        ports: set[int] = set()
        for token in re.split(r"[,\s]+", value.strip()):
            if not token:
                continue
            if token == "ssh":
                ports.add(22)
            elif token.isdigit() and 1 <= int(token) <= 65535:
                ports.add(int(token))
            else:
                return set()
        found = ports
    return found
