from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from app.command import run_command
from app.filesystem import write_atomic


UNATTENDED_UPGRADES = Path("/etc/apt/apt.conf.d/50unattended-upgrades")
MANAGED_SECURITY_UPDATES = Path("/etc/apt/apt.conf.d/90-vps-bootstrap-security-updates")


class SecurityUpdatesError(RuntimeError):
    def __init__(self, message: str, diagnostics: list[str] | None = None) -> None:
        super().__init__(message)
        self.diagnostics = diagnostics or ["apt-config dump APT::Periodic", "grep -R Automatic-Reboot /etc/apt/apt.conf.d", "test -f /var/run/reboot-required && cat /var/run/reboot-required"]


@dataclass(frozen=True)
class SecurityUpdatesStatus:
    enabled: bool
    automatic_reboot: bool
    reboot_required: bool
    security_origin: bool = False


def render_auto_upgrades() -> str:
    return "\n".join(
        [
            "// Managed by vps-bootstrap. Do not edit this file directly.",
            'APT::Periodic::Update-Package-Lists "1";',
            'APT::Periodic::Unattended-Upgrade "1";',
            'Unattended-Upgrade::Automatic-Reboot "false";',
            "",
        ]
    )


def parse_security_status(auto_content: str, unattended_content: str, reboot_required: bool = False) -> SecurityUpdatesStatus:
    enabled = 'APT::Periodic::Unattended-Upgrade "1"' in auto_content and 'APT::Periodic::Update-Package-Lists "1"' in auto_content
    reboot = 'Unattended-Upgrade::Automatic-Reboot "true"' in unattended_content
    security_origin = security_origin_from_text(unattended_content)
    return SecurityUpdatesStatus(enabled, reboot, reboot_required, security_origin)


def discover_security_updates() -> SecurityUpdatesStatus:
    apt_config = run_command(["apt-config", "dump"], timeout=10)
    if apt_config.ok:
        return parse_apt_config_status(apt_config.stdout, Path("/var/run/reboot-required").exists())
    managed = MANAGED_SECURITY_UPDATES.read_text(encoding="utf-8", errors="ignore") if MANAGED_SECURITY_UPDATES.exists() else ""
    return parse_security_status(managed, managed, Path("/var/run/reboot-required").exists())


def ensure_security_updates_from_state(data: dict, force_reconfigure: bool = False) -> dict:
    if data and data.get("mode") == "managed" and not force_reconfigure and verify_security_updates_state(data):
        return data
    result = run_command(["apt-get", "install", "-y", "unattended-upgrades"], timeout=120)
    if result.returncode not in {0, 127}:
        raise SecurityUpdatesError(f"Failed to install unattended-upgrades: {result.stderr or result.stdout}")
    if UNATTENDED_UPGRADES.exists() and "Managed by vps-bootstrap" in UNATTENDED_UPGRADES.read_text(encoding="utf-8", errors="ignore"):
        raise SecurityUpdatesError("Legacy vps-bootstrap-managed 50unattended-upgrades detected; manual review required before v0.2.0 can preserve distro config.")
    write_atomic(MANAGED_SECURITY_UPDATES, render_auto_upgrades(), 0o644)
    status = discover_security_updates()
    print_security_updates_status(status)
    state = {
        "mode": "managed",
        "enabled": status.enabled,
        "security_origin": status.security_origin,
        "automatic_reboot": status.automatic_reboot,
        "reboot_required": status.reboot_required,
    }
    if not status.enabled:
        raise SecurityUpdatesError("Effective APT policy does not enable periodic unattended upgrades.")
    if not status.security_origin:
        raise SecurityUpdatesError("Effective unattended-upgrades policy has no Ubuntu security origin; unrelated origin policy was not overwritten.")
    if status.automatic_reboot:
        raise SecurityUpdatesError("Effective unattended-upgrades policy still enables automatic reboot; conflicting later configuration was not overwritten.")
    return state


def verify_security_updates_state(data: dict) -> bool:
    if data.get("mode") == "skipped":
        return True
    if data.get("mode") != "managed":
        return False
    status = discover_security_updates()
    return status.enabled and status.security_origin and not status.automatic_reboot


def parse_apt_config_status(output: str, reboot_required: bool = False) -> SecurityUpdatesStatus:
    values: dict[str, str] = {}
    origin_values: list[str] = []
    for line in output.splitlines():
        stripped = line.strip().rstrip(";")
        if not stripped or " " not in stripped:
            continue
        key, raw_value = stripped.split(None, 1)
        value = raw_value.strip().strip('"')
        values[key] = value
        if key.startswith("Unattended-Upgrade::Allowed-Origins") or key.startswith("Unattended-Upgrade::Origins-Pattern"):
            origin_values.append(value)
    enabled = values.get("APT::Periodic::Update-Package-Lists") == "1" and values.get("APT::Periodic::Unattended-Upgrade") == "1"
    reboot = values.get("Unattended-Upgrade::Automatic-Reboot", "false").lower() == "true"
    security_origin = any(is_ubuntu_security_origin(value) for value in origin_values)
    return SecurityUpdatesStatus(enabled, reboot, reboot_required, security_origin)


def security_origin_from_text(content: str) -> bool:
    return any(
        is_ubuntu_security_origin(line)
        for line in content.splitlines()
        if "Allowed-Origins" in line or "Origins-Pattern" in line or "security" in line.lower()
    )


def is_ubuntu_security_origin(value: str) -> bool:
    normalized = value.lower().replace(" ", "")
    ubuntu_marker = "ubuntu" in normalized or "${distro_id}" in normalized or "origin=${distro_id}" in normalized
    return ubuntu_marker and "security" in normalized


def print_security_updates_status(status: SecurityUpdatesStatus) -> None:
    print(f"Security unattended upgrades enabled: {'yes' if status.enabled else 'no'}")
    print(f"Ubuntu security origin effective: {'yes' if status.security_origin else 'no'}")
    print(f"Automatic reboot enabled: {'yes' if status.automatic_reboot else 'no'}")
    print(f"Reboot required: {'yes' if status.reboot_required else 'no'}")
